### ISSUE TITLE
No module named 'bs4'

### ISSUE THREAD

**Issue by panomitrius** [degiz/kobo2calibre#1]
Getting the following error message when trying to run the code:

```
Traceback (most recent call last):
  File "/Users/panomitrius/kobo2calibre/parse_kobo_highlights.py", line 7, in <module>
    import calibre
  File "/Users/panomitrius/kobo2calibre/calibre.py", line 6, in <module>
    import bs4
ModuleNotFoundError: No module named 'bs4'
```

I have installed bs4 by running `python3 -m pip install beautifulsoup4` without any error messages. Running ` python3 -m pip show beautifulsoup4` returns:

```
Name: beautifulsoup4
Version: 4.11.1
Summary: Screen-scraping library
Home-page: https://www.crummy.com/software/BeautifulSoup/bs4/
Author: Leonard Richardson
Author-email: leonardr@segfault.org
License: MIT
Location: /usr/local/lib/python3.10/site-packages
Requires: soupsieve
Required-by: 
```

**Comment by panomitrius** [comment]
Managed to fix this with a virtual environment (https://www.youtube.com/watch?v=Kg1Yvry_Ydk&).

**Comment by degiz** [comment]
@panomitrius Great that you've resolved it!
I personally use `pyenv` for all of my python projects 👍
