### ISSUE TITLE
Add the possibility to export only a specific book

### ISSUE THREAD

**Issue by dalmo1991** [degiz/kobo2calibre#3]
Related to https://github.com/degiz/kobo2calibre/issues/2 , it could be useful to add the possibility of exporting a single specific book. This would be helpful when, for example, Calibre is not the only way one adds books to Kobo: in this case, Kobo and Calibre libraries will not be the same.

**Comment by degiz** [comment]
Hey @dalmo1991 

I agree; that makes a lot of sense for several reasons. 

I want to address this, but first step for me is to convert this tool to be a Calibre plugin. After that, I can reuse many built-in functionalities from Calibre itself, including checks "if the book is only in the device."

**Comment by degiz** [comment]
@dalmo1991 I'm almost done with a proper calibre plugin, that would work via GUI and allow to select individual books 🎉

**Comment by dalmo1991** [comment]
Cool. Thanks. Keep me updated when it's available!

**Comment by degiz** [comment]
Hey @dalmo1991 

I've just published [0.1 version](https://github.com/degiz/kobo2calibre/releases/tag/0.1), please give it a try!
I didn't write proper docs yet, but I hope the usage is straightforward enough.

**Comment by dalmo1991** [comment]
Crazy job man. It worked!
FYI, I had to install PyQt6 and the newer version of Calibre (6.10). Using Ubuntu 22.04.
Thanks!

**Comment by degiz** [comment]
I'm glad that it worked 🎉 

>  FYI, I had to install PyQt6 and the newer version of Calibre (6.10). Using Ubuntu 22.04.

Interesting, I expected it to come together with Calibre 🤔 I'll check, the plugin should work out-of-the-box

**Comment by dalmo1991** [comment]
RE PyQt6, I have installed it before updating Calibre (I had 5.**). Maybe with Calibre 6.10 you also get PyQt6...
