### ISSUE TITLE
CFI parser fails on recent Kobo

### ISSUE THREAD

**Issue by OddLingo** [degiz/kobo2calibre#7]
I have a Kobo Libra 2 with software 4.35.  The format it stores for highlight CFI strings seems to be different from what kobo2calibre expects.  I am seeing values like this: `index_split_000.html#point(/1/4/896/23:202)` and the `split` calls in  `parse_kobo_highlights` are not yielding the expected results.

The EPUB file is not  from kobo.com, but was uploaded from calibre.  But I created the highlight on the Libra 2 itself.

**Comment by degiz** [comment]
Hey @OddLingo 

Do you know how the kobo file was created? Quoting the README:
> Tested on the books converted using [calibre-kobo-driver](https://github.com/jgoguen/calibre-kobo-driver). Books converted using a different tool will most probably not work.

From my research, different `to-kobo` converters use different algorithms to split the sentences, and my converter only tested with calibre-kobo-driver.
